version: "3"
services:
  app:
    image: ghcr.io/dewey/webhook-receiver:master
    ports:
      - "8080:8080"
    environment:
      - WR_ENVIRONMENT=development
      - WR_PORT=8080
      - WR_CACHE_FILE_PATH=/cache
      - WR_FEED_URL=https://example.com/feed.xml
      - WR_HOOK_TOKEN=changeme
      - WR_TWITTER_CONSUMER_KEY=changeme
      - WR_TWITTER_CONSUMER_SECRET_KEY=changeme
      - WR_TWITTER_ACCESS_TOKEN=changeme
      - WR_TWITTER_ACCESS_TOKEN_SECRET=changeme
      - WR_TWITTER_USERNAME=changeme

    volumes:
      - /home/ubuntu/services/webhook-receiver/cache:/cache
